[project]
name = "escala-leitores-gerador"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Charles Duarte", email = "140444382+linduarte@users.noreply.github.com" },
]
requires-python = ">=3.14"
dependencies = [
    "click>=8.5.0",
    "matplotlib>=3.11.2",
    "openpyxl>=3.1.5",
    "pandas>=3.0.6",
    "pandas-stubs>=3.0.5.260914",
]

[project.scripts]
escala = "src.main:cli"
escala-leitores-gerador = "src.main:cli"

[tool.uv.build-backend]
module-name = "src"
module-root = ""

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "openpyxl-stubs>=0.1.25",
]
